### ISSUE TITLE
helm install prometheus start faild 

### ISSUE THREAD

**Issue by zhoushoujianwork** [flashcatcloud/n9e-helm#103]
```bash
ts=2023-12-22T03:51:58.343Z caller=main.go:172 level=warn msg="Remote write receiver enabled via feature flag remote-write-receiver. This is DEPRECATED. Use --web.enable-remote-write-receiver."
ts=2023-12-22T03:51:58.344Z caller=main.go:539 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-12-22T03:51:58.344Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.48.1, branch=HEAD, revision=63894216648f0d6be310c9d16fb48293c45c9310)"
ts=2023-12-22T03:51:58.344Z caller=main.go:588 level=info build_context="(go=go1.21.5, platform=linux/amd64, user=root@71f108ff5632, date=20231208-23:33:22, tags=netgo,builtinassets,stringlabels)"
ts=2023-12-22T03:51:58.344Z caller=main.go:589 level=info host_details="(Linux 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 nightingale-prometheus-0 (none))"
ts=2023-12-22T03:51:58.344Z caller=main.go:590 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-12-22T03:51:58.344Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-12-22T03:51:58.345Z caller=query_logger.go:93 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffd220916a5, 0xb}, 0x14, {0x3e94bc0, 0xc000a400f0})
	/app/promql/query_logger.go:123 +0x411
main.main()
	/app/cmd/prometheus/main.go:645 +0x7812
```

**Comment by zhoushoujianwork** [comment]
fix it add initContainers for statefulset
```yml
initContainers:
    - name: init-chmod
      image: busybox
      command: ['sh', '-c', 'chmod -R 777 /prometheus']
      volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
```
