### ISSUE TITLE
database启动失败

### ISSUE THREAD

**Issue by BigbigY** [flashcatcloud/n9e-helm#54]
Error: failed to start container "mysql": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/kubelet/pods/c5fcbc47-810e-4e1b-8423-35c41840151c/volumes/kubernetes.io~configmap/database-config" to rootfs at "/etc/my.cnf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```
database:
  type: internal
  internal:
    serviceAccountName: ""
    automountServiceAccountToken: false
    image:
      repository: docker.io/library/mysql
      tag: 5.7
    username: "root"
    password: "1234"
    shmSizeLimit: 512Mi
    nodeSelector: {}
    resources: {}
    tolerations: []
    affinity: {}
    priorityClassName:
    initContainer:
      migrator: {}
      permissions: {}
  maxIdleConns: 100
  maxOpenConns: 900
  podAnnotations: {}
```
